on:
  issues:
    types:
      - commented

name: Create an issue in Jira

jobs:
  create-issue-in-jira:
    name: Issue creation
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: find_comment
      with:
        issue-number: ${{  }}
        comment-author: github-actions[bot]
        direction: first
        nth: 0
        
    - name: Find Jira ticket
      if: steps.find_comment.outputs.comment-id != ''
      id: find_ticket
      uses: atlassian/gajira-find-issue-key@v3
      with:
        string: ${{ steps.find_comment.outputs.comment-id }}

    - name: Update Jira ticket
      if: steps.find_ticket.issue != ''
      uses: atlassian/gajira-comment@v3
      with:
        issue: ${{ steps.find_ticket.issue }}
        comment: 'Github issue was commented: \n\n ${{ github.event.comment.body }}'

      
